name: classroom_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter   


  cupertino_icons: ^1.0.8
  go_router: ^13.0.1
  provider: ^6.1.1
  get_it: ^7.2.0

  #icons & fonts & animations
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0

  #helper
  # url_strategy: ^0.2.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  
  #widgets
  # flutter_side_menu: ^0.4.0
  auto_size_text: ^3.0.0
  flutter_animated_dialog_updated: ^1.0.0
  cached_network_image: ^3.3.1
  flashy_tab_bar2: ^0.0.10
  dropdown_search: ^5.0.6
  ionicons: ^0.2.2
  rich_readmore: ^1.1.1
  skeletonizer: ^1.4.2
  
  #### syncfusion_flutter
  syncfusion_flutter_core: ^27.1.48
  syncfusion_localizations: ^27.1.48
  syncfusion_flutter_datagrid: ^27.1.48
  #firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.5.0

  
  flutter_side_menu: ^0.5.3
  device_info_plus: ^11.1.1

  intl: ^0.18.0
  collection: ^1.18.0
  emoji_picker_flutter: ^3.1.0
  file_picker: ^8.1.4
  path: ^1.9.0
  mime: ^2.0.0
  path_provider: ^2.1.5
  flutter_isolate: ^2.1.0
  universal_html: ^2.2.4
  dio: ^5.7.0
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  dynamic_path_url_strategy: ^1.0.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/icons/
  fonts: 
    - family: Mulish
      fonts: 
        - asset: assets/fonts/Mulish-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-ExtraBold.ttf
          weight: 800
